[package]
name = "file_sequencer"
version = "0.1.0"
authors = ["Blzbrg <randomparanoid@gmail.com>"]

[dependencies]
serde = { version = "1.0.110", features = ["derive"]}
serde_json = "1.0.53"

[lib]
name = "file_sequencer"
path = "src/lib.rs"
